// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnhAnY9TVbBOzXGJDoQbIWFU8L34Xntvw',
    appId: '1:613065775420:web:22ee749cea011d113de639',
    messagingSenderId: '613065775420',
    projectId: 'fitpoints-app-ittepic',
    authDomain: 'fitpoints-app-ittepic.firebaseapp.com',
    storageBucket: 'fitpoints-app-ittepic.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkoanQ68ltLP030HjHyuaGqwuzDYRaWQs',
    appId: '1:613065775420:ios:4c5d634feaf3e9883de639',
    messagingSenderId: '613065775420',
    projectId: 'fitpoints-app-ittepic',
    storageBucket: 'fitpoints-app-ittepic.firebasestorage.app',
    iosBundleId: 'mx.edu.ittepic.proyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnhAnY9TVbBOzXGJDoQbIWFU8L34Xntvw',
    appId: '1:613065775420:web:77acd4452b5c6aa13de639',
    messagingSenderId: '613065775420',
    projectId: 'fitpoints-app-ittepic',
    authDomain: 'fitpoints-app-ittepic.firebaseapp.com',
    storageBucket: 'fitpoints-app-ittepic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtF4E8a7ROY7h863kvJQkfipG0S45iSwo',
    appId: '1:240758500152:ios:87ef353f2ca6248cba6fcd',
    messagingSenderId: '240758500152',
    projectId: 'proyectofinal-d6fcd',
    databaseURL: 'https://proyectofinal-d6fcd-default-rtdb.firebaseio.com',
    storageBucket: 'proyectofinal-d6fcd.firebasestorage.app',
    iosBundleId: 'mx.edu.ittepic.proyectoFinal',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMat_SJhZns2Pzr9tgbqcwi4UIH3SOKOA',
    appId: '1:240758500152:android:b69010db2c5dde51ba6fcd',
    messagingSenderId: '240758500152',
    projectId: 'proyectofinal-d6fcd',
    databaseURL: 'https://proyectofinal-d6fcd-default-rtdb.firebaseio.com',
    storageBucket: 'proyectofinal-d6fcd.firebasestorage.app',
  );

}